//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_4.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: LED_4 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_4_INCLUDE
#define LED_4_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_4_Stop
#pragma fastcall16  LED_4_Start
#pragma fastcall16  LED_4_On
#pragma fastcall16  LED_4_Off
#pragma fastcall16  LED_4_Switch
#pragma fastcall16  LED_4_Invert
#pragma fastcall16  LED_4_GetState


//-------------------------------------------------
// Constants for LED_4 API's.
//-------------------------------------------------
//
#define  LED_4_ON   1
#define  LED_4_OFF  0

//-------------------------------------------------
// Prototypes of the LED_4 API.
//-------------------------------------------------
extern void  LED_4_Start(void);                                     
extern void  LED_4_Stop(void);                                      
extern void  LED_4_On(void);                                      
extern void  LED_4_Off(void);                                      
extern void  LED_4_Switch(BYTE bSwitch);
extern void  LED_4_Invert(void);                                         
extern BYTE  LED_4_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
