/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// P_10kHz address and mask defines
#pragma	ioport	P_10kHz_Data_ADDR:	0x0
BYTE			P_10kHz_Data_ADDR;
#pragma	ioport	P_10kHz_DriveMode_0_ADDR:	0x100
BYTE			P_10kHz_DriveMode_0_ADDR;
#pragma	ioport	P_10kHz_DriveMode_1_ADDR:	0x101
BYTE			P_10kHz_DriveMode_1_ADDR;
#pragma	ioport	P_10kHz_DriveMode_2_ADDR:	0x3
BYTE			P_10kHz_DriveMode_2_ADDR;
#pragma	ioport	P_10kHz_GlobalSelect_ADDR:	0x2
BYTE			P_10kHz_GlobalSelect_ADDR;
#pragma	ioport	P_10kHz_IntCtrl_0_ADDR:	0x102
BYTE			P_10kHz_IntCtrl_0_ADDR;
#pragma	ioport	P_10kHz_IntCtrl_1_ADDR:	0x103
BYTE			P_10kHz_IntCtrl_1_ADDR;
#pragma	ioport	P_10kHz_IntEn_ADDR:	0x1
BYTE			P_10kHz_IntEn_ADDR;
#define P_10kHz_MASK 0x20
// SERVO address and mask defines
#pragma	ioport	SERVO_Data_ADDR:	0x0
BYTE			SERVO_Data_ADDR;
#pragma	ioport	SERVO_DriveMode_0_ADDR:	0x100
BYTE			SERVO_DriveMode_0_ADDR;
#pragma	ioport	SERVO_DriveMode_1_ADDR:	0x101
BYTE			SERVO_DriveMode_1_ADDR;
#pragma	ioport	SERVO_DriveMode_2_ADDR:	0x3
BYTE			SERVO_DriveMode_2_ADDR;
#pragma	ioport	SERVO_GlobalSelect_ADDR:	0x2
BYTE			SERVO_GlobalSelect_ADDR;
#pragma	ioport	SERVO_IntCtrl_0_ADDR:	0x102
BYTE			SERVO_IntCtrl_0_ADDR;
#pragma	ioport	SERVO_IntCtrl_1_ADDR:	0x103
BYTE			SERVO_IntCtrl_1_ADDR;
#pragma	ioport	SERVO_IntEn_ADDR:	0x1
BYTE			SERVO_IntEn_ADDR;
#define SERVO_MASK 0x40
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0x4
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0x5
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x1
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_2Pin address and mask defines
#pragma	ioport	LED_2Pin_Data_ADDR:	0x4
BYTE			LED_2Pin_Data_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_2Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_2Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_2Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_2Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_2Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_2Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_2Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_2Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_2Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_2Pin_IntEn_ADDR:	0x5
BYTE			LED_2Pin_IntEn_ADDR;
#define LED_2Pin_MASK 0x2
// LED_2Pin Shadow defines
//   LED_2Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_2Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_3Pin address and mask defines
#pragma	ioport	LED_3Pin_Data_ADDR:	0x4
BYTE			LED_3Pin_Data_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_3Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_3Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_3Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_3Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_3Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_3Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_3Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_3Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_3Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_3Pin_IntEn_ADDR:	0x5
BYTE			LED_3Pin_IntEn_ADDR;
#define LED_3Pin_MASK 0x4
// LED_3Pin Shadow defines
//   LED_3Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_3Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_4Pin address and mask defines
#pragma	ioport	LED_4Pin_Data_ADDR:	0x4
BYTE			LED_4Pin_Data_ADDR;
#pragma	ioport	LED_4Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_4Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_4Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_4Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_4Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_4Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_4Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_4Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_4Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_4Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_4Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_4Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_4Pin_IntEn_ADDR:	0x5
BYTE			LED_4Pin_IntEn_ADDR;
#define LED_4Pin_MASK 0x8
// LED_4Pin Shadow defines
//   LED_4Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_4Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
